### ISSUE TITLE
Individual RP Stats

### ISSUE THREAD

**Issue by tecknojock** [xiagu/jekyll-rp-logs#51] opened 2015-11-11 19:47 UTC
I'd be nice to get a count of posts, words, Average character count per RPer, Time spent, and number of RP sessions.

**Comment by irisfofs** [comment] 2015-11-11 19:48
Duplicate of #34

**Comment by tecknojock** [comment] 2015-11-11 19:49
This is not a duplicate I dont think. That one is aggregate for the site is it not?

**Closed as completed by irisfofs** 2015-11-11 19:48 UTC
Labels: duplicate

**Comment by irisfofs** [comment] 2015-11-11 19:50
Perhaps the additional details have just been in my head, then, but I'd intended similar statistics available per-page as well.
